[2022-06-21 09:00:13,164] [INFO] [MainThread] [django.utils.autoreload] | C:\Users\lenovo\Desktop\workspace\django-controller\sse\celery_job\tasks.py changed, reloading.
[2022-06-21 09:06:20,611] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Pika version 1.2.1 connecting to ('192.168.246.128', 5672)
[2022-06-21 09:06:20,634] [INFO] [MainThread] [pika.adapters.utils.io_services_utils] | Socket connected: <socket.socket fd=1412, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.246.1', 52516), raddr=('192.168.246.128', 5672)>
[2022-06-21 09:06:20,635] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000002C55FE92170>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000002C55FE92170> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>).
[2022-06-21 09:06:20,644] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000002C55FE92170> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 09:06:20,645] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000002C55FE92170> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 09:06:20,645] [INFO] [MainThread] [pika.adapters.blocking_connection] | Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000002C55FE92170> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 09:06:20,647] [INFO] [MainThread] [pika.adapters.blocking_connection] | Created channel=1
[2022-06-21 09:07:13,691] [INFO] [Thread-1 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /user/login/ with method: POST
[2022-06-21 09:07:15,529] [INFO] [Thread-2 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 09:07:15,543] [INFO] [Thread-3 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 09:07:15,561] [INFO] [Thread-4 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 09:07:19,075] [INFO] [Thread-5 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 09:07:20,074] [INFO] [Thread-6 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /user/login/ with method: POST
[2022-06-21 09:12:44,744] [INFO] [Thread-7 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 09:17:12,334] [INFO] [Thread-8 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 09:19:44,155] [INFO] [Thread-9 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 09:22:01,589] [INFO] [MainThread] [django.utils.autoreload] | C:\Users\lenovo\Desktop\workspace\django-controller\sse\celery_job\tasks.py changed, reloading.
[2022-06-21 09:23:09,199] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Pika version 1.2.1 connecting to ('192.168.246.128', 5672)
[2022-06-21 09:23:09,223] [INFO] [MainThread] [pika.adapters.utils.io_services_utils] | Socket connected: <socket.socket fd=780, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.246.1', 63283), raddr=('192.168.246.128', 5672)>
[2022-06-21 09:23:09,224] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000024FB2696170>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000024FB2696170> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>).
[2022-06-21 09:23:09,232] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000024FB2696170> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 09:23:09,233] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000024FB2696170> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 09:23:09,234] [INFO] [MainThread] [pika.adapters.blocking_connection] | Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000024FB2696170> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 09:23:09,234] [INFO] [MainThread] [pika.adapters.blocking_connection] | Created channel=1
[2022-06-21 09:23:48,261] [INFO] [Thread-1 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 09:23:49,267] [INFO] [Thread-2 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /user/login/ with method: POST
[2022-06-21 09:34:45,897] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Pika version 1.2.1 connecting to ('192.168.246.128', 5672)
[2022-06-21 09:34:45,899] [INFO] [MainThread] [pika.adapters.utils.io_services_utils] | Socket connected: <socket.socket fd=1664, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.246.1', 62627), raddr=('192.168.246.128', 5672)>
[2022-06-21 09:34:45,900] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000018030A26170>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000018030A26170> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>).
[2022-06-21 09:34:45,907] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000018030A26170> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 09:34:45,907] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000018030A26170> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 09:34:45,908] [INFO] [MainThread] [pika.adapters.blocking_connection] | Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000018030A26170> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 09:34:45,908] [INFO] [MainThread] [pika.adapters.blocking_connection] | Created channel=1
[2022-06-21 09:37:25,773] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Pika version 1.2.1 connecting to ('192.168.246.128', 5672)
[2022-06-21 09:37:25,774] [INFO] [MainThread] [pika.adapters.utils.io_services_utils] | Socket connected: <socket.socket fd=1548, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.246.1', 49791), raddr=('192.168.246.128', 5672)>
[2022-06-21 09:37:25,776] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000215E7CE6170>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000215E7CE6170> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>).
[2022-06-21 09:37:25,786] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000215E7CE6170> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 09:37:25,787] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000215E7CE6170> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 09:37:25,787] [INFO] [MainThread] [pika.adapters.blocking_connection] | Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000215E7CE6170> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 09:37:25,787] [INFO] [MainThread] [pika.adapters.blocking_connection] | Created channel=1
[2022-06-21 09:37:42,873] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Pika version 1.2.1 connecting to ('192.168.246.128', 5672)
[2022-06-21 09:37:42,896] [INFO] [MainThread] [pika.adapters.utils.io_services_utils] | Socket connected: <socket.socket fd=1168, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.246.1', 57964), raddr=('192.168.246.128', 5672)>
[2022-06-21 09:37:42,897] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000022B9EC361A0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000022B9EC361A0> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>).
[2022-06-21 09:37:42,907] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000022B9EC361A0> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 09:37:42,907] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000022B9EC361A0> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 09:37:42,908] [INFO] [MainThread] [pika.adapters.blocking_connection] | Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000022B9EC361A0> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 09:37:42,908] [INFO] [MainThread] [pika.adapters.blocking_connection] | Created channel=1
[2022-06-21 09:38:21,089] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Pika version 1.2.1 connecting to ('192.168.246.128', 5672)
[2022-06-21 09:38:21,091] [INFO] [MainThread] [pika.adapters.utils.io_services_utils] | Socket connected: <socket.socket fd=1076, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.246.1', 52880), raddr=('192.168.246.128', 5672)>
[2022-06-21 09:38:21,092] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000020A9C556170>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000020A9C556170> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>).
[2022-06-21 09:38:21,100] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000020A9C556170> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 09:38:21,100] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000020A9C556170> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 09:38:21,100] [INFO] [MainThread] [pika.adapters.blocking_connection] | Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000020A9C556170> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 09:38:21,102] [INFO] [MainThread] [pika.adapters.blocking_connection] | Created channel=1
[2022-06-21 09:38:21,109] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_007FD15D173B42E0957BFC5F94B2CB6D', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_007FD15D173B42E0957BFC5F94B2CB6D/EXEC_007FD15D173B42E0957BFC5F94B2CB6D.html', 'duration': '0.15'}.
[2022-06-21 09:38:34,043] [INFO] [Thread-3 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 10:37:19,237] [INFO] [MainThread] [django.utils.autoreload] | C:\Users\lenovo\Desktop\workspace\django-controller\sse\celery_job\tasks.py changed, reloading.
[2022-06-21 10:38:08,113] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Pika version 1.2.1 connecting to ('192.168.246.128', 5672)
[2022-06-21 10:38:08,136] [INFO] [MainThread] [pika.adapters.utils.io_services_utils] | Socket connected: <socket.socket fd=1252, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.246.1', 50494), raddr=('192.168.246.128', 5672)>
[2022-06-21 10:38:08,137] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001D7F3FAA050>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001D7F3FAA050> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>).
[2022-06-21 10:38:08,145] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001D7F3FAA050> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 10:38:08,146] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001D7F3FAA050> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 10:38:08,146] [INFO] [MainThread] [pika.adapters.blocking_connection] | Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001D7F3FAA050> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 10:38:08,146] [INFO] [MainThread] [pika.adapters.blocking_connection] | Created channel=1
[2022-06-21 10:38:08,251] [INFO] [MainThread] [sse.lib.utils.logger] | Waiting for response from execution engine.
[2022-06-21 10:38:21,673] [INFO] [Thread-1 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 10:39:37,639] [INFO] [Thread-2 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /user/login/ with method: POST
[2022-06-21 10:39:38,100] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_6CFE158045664B459E419F2A888CBC07', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_6CFE158045664B459E419F2A888CBC07/EXEC_6CFE158045664B459E419F2A888CBC07.html', 'duration': '0.15'}.
[2022-06-21 10:40:39,099] [INFO] [Thread-3 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/348e557234fc40369e873de585207bb4/ with method: GET
[2022-06-21 10:40:42,613] [INFO] [Thread-4 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 10:43:48,619] [INFO] [MainThread] [django.utils.autoreload] | C:\Users\lenovo\Desktop\workspace\django-controller\sse\celery_job\tasks.py changed, reloading.
[2022-06-21 10:43:50,077] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Pika version 1.2.1 connecting to ('192.168.246.128', 5672)
[2022-06-21 10:43:50,080] [INFO] [MainThread] [pika.adapters.utils.io_services_utils] | Socket connected: <eventlet.greenio.base.GreenSocket object at 0x0000020C58252D10>
[2022-06-21 10:43:50,081] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000020C58253AF0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000020C58253AF0> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>).
[2022-06-21 10:43:50,092] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000020C58253AF0> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 10:43:50,093] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000020C58253AF0> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 10:43:50,093] [INFO] [MainThread] [pika.adapters.blocking_connection] | Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000020C58253AF0> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 10:43:50,094] [INFO] [MainThread] [pika.adapters.blocking_connection] | Created channel=1
[2022-06-21 10:45:44,208] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Pika version 1.2.1 connecting to ('192.168.246.128', 5672)
[2022-06-21 10:45:44,209] [INFO] [MainThread] [pika.adapters.utils.io_services_utils] | Socket connected: <socket.socket fd=1084, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.246.1', 49896), raddr=('192.168.246.128', 5672)>
[2022-06-21 10:45:44,210] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000011BF07F3A90>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000011BF07F3A90> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>).
[2022-06-21 10:45:44,220] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000011BF07F3A90> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 10:45:44,221] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000011BF07F3A90> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 10:45:44,221] [INFO] [MainThread] [pika.adapters.blocking_connection] | Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000011BF07F3A90> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 10:45:44,222] [INFO] [MainThread] [pika.adapters.blocking_connection] | Created channel=1
[2022-06-21 10:45:44,504] [INFO] [MainThread] [sse.lib.utils.logger] | Waiting for response from execution engine.
[2022-06-21 10:45:49,139] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Pika version 1.2.1 connecting to ('192.168.246.128', 5672)
[2022-06-21 10:45:49,152] [INFO] [MainThread] [pika.adapters.utils.io_services_utils] | Socket connected: <eventlet.greenio.base.GreenSocket object at 0x000001A3D27673A0>
[2022-06-21 10:45:49,153] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001A3D2619120>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001A3D2619120> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>).
[2022-06-21 10:45:49,162] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001A3D2619120> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 10:45:49,163] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001A3D2619120> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 10:45:49,164] [INFO] [MainThread] [pika.adapters.blocking_connection] | Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x000001A3D2619120> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 10:45:49,165] [INFO] [MainThread] [pika.adapters.blocking_connection] | Created channel=1
[2022-06-21 10:45:58,537] [INFO] [Thread-2 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 10:45:59,213] [INFO] [Thread-3 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /user/login/ with method: POST
[2022-06-21 10:47:02,158] [INFO] [Thread-4 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 10:50:52,437] [INFO] [MainThread] [django.utils.autoreload] | C:\Users\lenovo\Desktop\workspace\django-controller\sse\celery_job\tasks.py changed, reloading.
[2022-06-21 10:51:17,402] [INFO] [Thread-1 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 10:51:18,100] [INFO] [Thread-2 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /user/login/ with method: POST
[2022-06-21 10:51:18,548] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_6E2D6472B0AA4205B14ED2DAE843F6F8', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_6E2D6472B0AA4205B14ED2DAE843F6F8/EXEC_6E2D6472B0AA4205B14ED2DAE843F6F8.html', 'duration': '0.15'}.
[2022-06-21 10:51:28,468] [INFO] [Thread-3 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 11:04:40,517] [INFO] [MainThread] [django.utils.autoreload] | C:\Users\lenovo\Desktop\workspace\django-controller\sse\celery_job\tasks.py changed, reloading.
[2022-06-21 11:05:13,614] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Pika version 1.2.1 connecting to ('192.168.246.128', 5672)
[2022-06-21 11:05:13,615] [INFO] [MainThread] [pika.adapters.utils.io_services_utils] | Socket connected: <socket.socket fd=1168, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.246.1', 58653), raddr=('192.168.246.128', 5672)>
[2022-06-21 11:05:13,616] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000233362BA080>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000233362BA080> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>).
[2022-06-21 11:05:13,622] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000233362BA080> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 11:05:13,623] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000233362BA080> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 11:05:13,624] [INFO] [MainThread] [pika.adapters.blocking_connection] | Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000233362BA080> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 11:05:13,624] [INFO] [MainThread] [pika.adapters.blocking_connection] | Created channel=1
[2022-06-21 11:05:13,629] [INFO] [MainThread] [sse.lib.utils.logger] | Waiting for response from execution engine.
[2022-06-21 11:05:28,607] [INFO] [Thread-1 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 11:05:29,479] [INFO] [Thread-2 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /user/login/ with method: POST
[2022-06-21 11:05:29,754] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_895B57BC714244B6BCC8771A563146F3', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_895B57BC714244B6BCC8771A563146F3/EXEC_895B57BC714244B6BCC8771A563146F3.html', 'duration': '0.15'}.
[2022-06-21 11:05:43,787] [INFO] [Thread-3 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 11:05:44,445] [INFO] [Thread-4 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /user/login/ with method: POST
[2022-06-21 11:05:44,970] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_09F5E0A83B3A41E491F9576C96F57045', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_09F5E0A83B3A41E491F9576C96F57045/EXEC_09F5E0A83B3A41E491F9576C96F57045.html', 'duration': '0.15'}.
[2022-06-21 11:06:02,372] [INFO] [Thread-6 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 11:06:02,398] [INFO] [Thread-5 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 11:06:02,406] [INFO] [Thread-7 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 11:06:08,318] [INFO] [Thread-8 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 11:06:09,082] [INFO] [Thread-9 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /user/login/ with method: POST
[2022-06-21 11:06:09,533] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_A2D6BA7F68234BF0A8B83FF81C356876', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_A2D6BA7F68234BF0A8B83FF81C356876/EXEC_A2D6BA7F68234BF0A8B83FF81C356876.html', 'duration': '0.15'}.
[2022-06-21 11:06:18,771] [INFO] [Thread-10 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/project/ with method: GET
[2022-06-21 11:06:20,982] [INFO] [Thread-11 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/ with method: GET
[2022-06-21 11:06:23,519] [INFO] [Thread-12 (process_request_thread)] [sse.lib.utils.logger] | 220 (vsFTPd 3.0.3)
[2022-06-21 11:06:23,755] [INFO] [Thread-12 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report-details/view/ with method: POST
[2022-06-21 11:09:19,288] [INFO] [MainThread] [django.utils.autoreload] | C:\Users\lenovo\Desktop\workspace\django-controller\sse\celery_job\tasks.py changed, reloading.
[2022-06-21 11:12:10,811] [INFO] [MainThread] [django.utils.autoreload] | C:\Users\lenovo\Desktop\workspace\django-controller\sse\lib\utils\rabbitMq.py changed, reloading.
[2022-06-21 11:29:55,268] [INFO] [Thread-3 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 11:29:55,275] [INFO] [Thread-1 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 11:29:55,284] [INFO] [Thread-2 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 11:30:02,260] [INFO] [Thread-4 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 11:30:07,173] [INFO] [Thread-5 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 11:30:07,213] [INFO] [Thread-6 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/scenario/ with method: GET
[2022-06-21 11:30:09,083] [INFO] [Thread-7 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/ with method: GET
[2022-06-21 11:39:30,550] [INFO] [Thread-8 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/?remark=&statue=&person=&type=&create_time=&start=&end= with method: GET
[2022-06-21 11:39:31,055] [INFO] [Thread-9 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/?remark=&statue=&person=&type=&create_time=&start=&end= with method: GET
[2022-06-21 11:39:31,260] [INFO] [Thread-10 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/?remark=&statue=&person=&type=&create_time=&start=&end= with method: GET
[2022-06-21 11:39:57,389] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Pika version 1.2.1 connecting to ('192.168.246.128', 5672)
[2022-06-21 11:39:57,390] [INFO] [MainThread] [pika.adapters.utils.io_services_utils] | Socket connected: <socket.socket fd=1444, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.246.1', 56403), raddr=('192.168.246.128', 5672)>
[2022-06-21 11:39:57,391] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000020DA583A080>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000020DA583A080> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>).
[2022-06-21 11:39:57,399] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000020DA583A080> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 11:39:57,399] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000020DA583A080> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 11:39:57,400] [INFO] [MainThread] [pika.adapters.blocking_connection] | Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000020DA583A080> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 11:39:57,401] [INFO] [MainThread] [pika.adapters.blocking_connection] | Created channel=1
[2022-06-21 11:39:57,407] [INFO] [MainThread] [sse.lib.utils.logger] | Waiting for response from execution engine.
[2022-06-21 11:40:03,541] [INFO] [Thread-1 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 11:40:03,603] [INFO] [Thread-2 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/scenario/ with method: GET
[2022-06-21 11:40:06,577] [INFO] [Thread-4 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 11:40:06,604] [INFO] [Thread-3 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 11:40:06,626] [INFO] [Thread-5 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 11:40:09,742] [INFO] [Thread-6 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 12:26:07,803] [INFO] [Thread-7 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 12:33:18,476] [INFO] [Thread-8 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 12:33:21,118] [INFO] [Thread-9 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/ with method: GET
[2022-06-21 12:33:23,414] [INFO] [Thread-10 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/?remark=&statue=&person=&type=&create_time=&start=&end= with method: GET
[2022-06-21 12:33:24,252] [INFO] [Thread-11 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/?remark=&statue=&person=&type=&create_time=&start=&end= with method: GET
[2022-06-21 12:33:48,734] [INFO] [Thread-12 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/?remark=&statue=&person=&type=&create_time=&start=&end= with method: GET
[2022-06-21 12:33:50,556] [INFO] [Thread-13 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 12:33:50,608] [INFO] [Thread-14 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/scenario/ with method: GET
[2022-06-21 12:33:51,134] [INFO] [Thread-16 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 12:33:51,146] [INFO] [Thread-15 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 12:33:51,173] [INFO] [Thread-17 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 12:33:57,411] [INFO] [Thread-18 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 12:34:03,725] [INFO] [Thread-19 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/ with method: GET
[2022-06-21 12:34:09,933] [INFO] [Thread-20 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/ with method: GET
[2022-06-21 12:35:31,216] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Pika version 1.2.1 connecting to ('192.168.246.128', 5672)
[2022-06-21 12:35:31,235] [INFO] [MainThread] [pika.adapters.utils.io_services_utils] | Socket connected: <socket.socket fd=1112, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.246.1', 55981), raddr=('192.168.246.128', 5672)>
[2022-06-21 12:35:31,236] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000202A02FA080>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000202A02FA080> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>).
[2022-06-21 12:35:31,370] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000202A02FA080> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 12:35:31,370] [INFO] [MainThread] [pika.adapters.utils.connection_workflow] | AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000202A02FA080> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 12:35:31,371] [INFO] [MainThread] [pika.adapters.blocking_connection] | Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x00000202A02FA080> params=<ConnectionParameters host=192.168.246.128 port=5672 virtual_host=report ssl=False>>
[2022-06-21 12:35:31,371] [INFO] [MainThread] [pika.adapters.blocking_connection] | Created channel=1
[2022-06-21 12:35:31,378] [INFO] [MainThread] [sse.lib.utils.logger] | Waiting for response from execution engine.
[2022-06-21 12:36:50,405] [INFO] [Thread-21 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 12:36:50,439] [INFO] [Thread-22 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/scenario/ with method: GET
[2022-06-21 12:36:54,445] [INFO] [Thread-24 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 12:36:54,471] [INFO] [Thread-25 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 12:36:54,480] [INFO] [Thread-23 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 12:36:57,682] [INFO] [Thread-26 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 13:01:24,202] [INFO] [Thread-27 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 13:23:32,420] [INFO] [Thread-28 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 13:23:33,417] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_CCCD132FEE6443D4853DCF5A8C91F257', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_CCCD132FEE6443D4853DCF5A8C91F257/EXEC_CCCD132FEE6443D4853DCF5A8C91F257.html', 'duration': '0.15'}.
[2022-06-21 13:33:17,438] [INFO] [Thread-29 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 13:33:18,354] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_45EB7B3E60484A1392CE5C03EF874274', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_45EB7B3E60484A1392CE5C03EF874274/EXEC_45EB7B3E60484A1392CE5C03EF874274.html', 'duration': '0.15'}.
[2022-06-21 13:33:25,631] [INFO] [Thread-30 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 13:33:26,304] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_C7A2F639E7F8414A92083C8F70116071', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_C7A2F639E7F8414A92083C8F70116071/EXEC_C7A2F639E7F8414A92083C8F70116071.html', 'duration': '0.15'}.
[2022-06-21 13:33:39,419] [INFO] [Thread-31 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 13:33:40,035] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_15B0E8A6B618404D91642B37D88C0372', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_15B0E8A6B618404D91642B37D88C0372/EXEC_15B0E8A6B618404D91642B37D88C0372.html', 'duration': '0.15'}.
[2022-06-21 13:33:45,159] [INFO] [Thread-32 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 13:33:45,725] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_69029E257AAB4EB99D89051DAC48886F', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_69029E257AAB4EB99D89051DAC48886F/EXEC_69029E257AAB4EB99D89051DAC48886F.html', 'duration': '0.15'}.
[2022-06-21 13:33:47,437] [INFO] [Thread-33 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/ with method: GET
[2022-06-21 13:33:50,291] [INFO] [Thread-34 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/?remark=&statue=&person=&type=&create_time=&start=&end= with method: GET
[2022-06-21 13:33:51,566] [INFO] [Thread-35 (process_request_thread)] [sse.lib.utils.logger] | 220 (vsFTPd 3.0.3)
[2022-06-21 13:33:51,578] [INFO] [Thread-35 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report-details/view/ with method: POST
[2022-06-21 13:33:55,088] [INFO] [Thread-36 (process_request_thread)] [sse.lib.utils.logger] | 220 (vsFTPd 3.0.3)
[2022-06-21 13:33:55,098] [INFO] [Thread-36 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report-details/view/ with method: POST
[2022-06-21 13:34:03,545] [INFO] [Thread-37 (process_request_thread)] [sse.lib.utils.logger] | 220 (vsFTPd 3.0.3)
[2022-06-21 13:34:03,553] [INFO] [Thread-37 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report-details/view/ with method: POST
[2022-06-21 13:34:17,660] [INFO] [Thread-38 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 13:34:21,386] [INFO] [Thread-39 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/project/ with method: GET
[2022-06-21 13:34:24,629] [INFO] [Thread-41 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 13:34:24,660] [INFO] [Thread-40 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 13:34:24,681] [INFO] [Thread-42 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 13:38:10,998] [INFO] [Thread-43 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 13:38:11,007] [INFO] [Thread-44 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/scenario/ with method: GET
[2022-06-21 13:59:55,918] [INFO] [Thread-45 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/ with method: GET
[2022-06-21 14:00:35,626] [INFO] [Thread-46 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/?page=3 with method: GET
[2022-06-21 14:00:41,799] [INFO] [Thread-47 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/?page=2 with method: GET
[2022-06-21 14:00:45,827] [INFO] [Thread-48 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/?page=3 with method: GET
[2022-06-21 14:00:46,801] [INFO] [Thread-49 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/?page=4 with method: GET
[2022-06-21 14:00:48,688] [INFO] [Thread-50 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/?page=5 with method: GET
[2022-06-21 14:00:51,403] [INFO] [Thread-51 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/?page=1 with method: GET
[2022-06-21 14:06:18,490] [INFO] [Thread-53 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 14:06:18,523] [INFO] [Thread-52 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 14:06:18,533] [INFO] [Thread-54 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 14:06:20,513] [INFO] [Thread-55 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 14:06:20,523] [INFO] [Thread-56 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/scenario/ with method: GET
[2022-06-21 14:06:21,956] [INFO] [Thread-57 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 14:06:23,274] [INFO] [Thread-58 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/project/ with method: GET
[2022-06-21 14:06:38,214] [INFO] [Thread-59 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/project/b17df0d9f31342e28e1530675e0eaca0/ with method: PUT
[2022-06-21 14:06:38,287] [INFO] [Thread-60 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/project/ with method: GET
[2022-06-21 14:07:03,791] [INFO] [Thread-61 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 14:07:05,092] [INFO] [Thread-63 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/scenario/ with method: GET
[2022-06-21 14:07:05,100] [INFO] [Thread-62 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 14:07:35,109] [INFO] [Thread-64 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 14:08:09,408] [INFO] [Thread-65 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/project/ with method: GET
[2022-06-21 14:08:16,986] [INFO] [Thread-66 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 14:08:17,200] [INFO] [Thread-67 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 14:08:17,237] [INFO] [Thread-68 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/scenario/ with method: GET
[2022-06-21 14:08:21,471] [INFO] [Thread-70 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 14:08:21,514] [INFO] [Thread-69 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 14:08:21,529] [INFO] [Thread-71 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 14:52:02,730] [INFO] [Thread-72 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/project/ with method: GET
[2022-06-21 14:52:02,751] [INFO] [Thread-73 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 14:52:06,552] [INFO] [Thread-74 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 14:52:07,338] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_82A36025787F4139AE1BE7662348976F', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_82A36025787F4139AE1BE7662348976F/EXEC_82A36025787F4139AE1BE7662348976F.html', 'duration': '0.15'}.
[2022-06-21 14:52:36,757] [INFO] [Thread-75 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/ with method: GET
[2022-06-21 14:52:38,965] [INFO] [Thread-76 (process_request_thread)] [sse.lib.utils.logger] | 220 (vsFTPd 3.0.3)
[2022-06-21 14:52:38,982] [INFO] [Thread-76 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report-details/view/ with method: POST
[2022-06-21 14:54:58,824] [INFO] [Thread-77 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /user/info/ with method: GET
[2022-06-21 14:55:44,694] [INFO] [Thread-78 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /user/register/ with method: POST
[2022-06-21 14:55:48,127] [INFO] [Thread-79 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /user/info/?user_id=&is_active= with method: GET
[2022-06-21 14:56:01,610] [INFO] [Thread-80 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /user/login/ with method: POST
[2022-06-21 14:56:10,401] [INFO] [Thread-81 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /user/info/ with method: GET
[2022-06-21 14:56:11,236] [INFO] [Thread-83 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 14:56:11,367] [INFO] [Thread-82 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/project/ with method: GET
[2022-06-21 14:56:16,096] [INFO] [Thread-84 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 14:56:18,488] [INFO] [Thread-85 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 14:56:18,518] [INFO] [Thread-86 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 14:56:18,557] [INFO] [Thread-87 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 14:56:20,266] [INFO] [Thread-88 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/project/ with method: GET
[2022-06-21 14:56:23,310] [INFO] [Thread-89 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/project/ with method: GET
[2022-06-21 14:56:23,394] [INFO] [Thread-90 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 14:56:24,364] [INFO] [Thread-91 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/project/ with method: GET
[2022-06-21 14:56:27,256] [INFO] [Thread-92 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/project/ with method: GET
[2022-06-21 14:56:27,299] [INFO] [Thread-93 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 14:56:35,616] [INFO] [Thread-94 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 14:56:36,340] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_7BAFD11668624AD69798E33952525B95', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_7BAFD11668624AD69798E33952525B95/EXEC_7BAFD11668624AD69798E33952525B95.html', 'duration': '0.15'}.
[2022-06-21 14:56:39,234] [INFO] [Thread-95 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/ with method: GET
[2022-06-21 14:56:43,635] [INFO] [Thread-96 (process_request_thread)] [sse.lib.utils.logger] | 220 (vsFTPd 3.0.3)
[2022-06-21 14:56:43,643] [INFO] [Thread-96 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report-details/view/ with method: POST
[2022-06-21 14:56:51,167] [INFO] [Thread-97 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/project/ with method: GET
[2022-06-21 14:57:06,230] [INFO] [Thread-98 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/project/ with method: GET
[2022-06-21 14:57:06,260] [INFO] [Thread-99 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 14:57:35,390] [INFO] [Thread-100 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 14:57:37,224] [INFO] [Thread-101 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 14:57:37,253] [INFO] [Thread-102 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 14:57:37,291] [INFO] [Thread-103 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 14:57:38,756] [INFO] [Thread-104 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 14:57:38,774] [INFO] [Thread-105 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/scenario/ with method: GET
[2022-06-21 14:57:48,674] [INFO] [Thread-106 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/parameter-fields/ with method: POST
[2022-06-21 14:58:54,199] [INFO] [Thread-107 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/scenario/ with method: POST
[2022-06-21 14:58:54,277] [INFO] [Thread-108 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/scenario/ with method: GET
[2022-06-21 14:58:58,253] [INFO] [Thread-109 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 14:58:58,258] [INFO] [Thread-110 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 14:58:58,295] [INFO] [Thread-111 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 14:59:07,284] [INFO] [Thread-112 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/0c758c426d4d42c8bfe54cf9badff477/ with method: GET
[2022-06-21 14:59:17,360] [INFO] [Thread-113 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 14:59:18,310] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_A4B3587CA22B47E7896A8BBBEB9FA0E8', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_A4B3587CA22B47E7896A8BBBEB9FA0E8/EXEC_A4B3587CA22B47E7896A8BBBEB9FA0E8.html', 'duration': '0.15'}.
[2022-06-21 14:59:20,173] [INFO] [Thread-114 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 14:59:20,180] [INFO] [Thread-115 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 14:59:20,208] [INFO] [Thread-116 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 14:59:21,608] [INFO] [Thread-117 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 14:59:21,665] [INFO] [Thread-118 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/scenario/ with method: GET
[2022-06-21 14:59:22,420] [INFO] [Thread-119 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/ with method: GET
[2022-06-21 14:59:24,170] [INFO] [Thread-120 (process_request_thread)] [sse.lib.utils.logger] | 220 (vsFTPd 3.0.3)
[2022-06-21 14:59:24,179] [INFO] [Thread-120 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report-details/view/ with method: POST
[2022-06-21 14:59:45,278] [INFO] [Thread-121 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 14:59:45,308] [INFO] [Thread-122 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 14:59:45,350] [INFO] [Thread-123 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 14:59:46,436] [INFO] [Thread-124 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 14:59:46,446] [INFO] [Thread-125 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/scenario/ with method: GET
[2022-06-21 15:00:27,621] [ERROR] [Thread-126 (process_request_thread)] [django.request] | Internal Server Error: /api/scenario/9dc6ad3b71fc425f8ff7fd49de20284f/
Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\lenovo\Desktop\workspace\django-controller\sse\lib\core\model_view_set.py", line 19, in update
    response = super().update(request, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\mixins.py", line 65, in update
    instance = self.get_object()
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 346, in check_object_permissions
    self.permission_denied(
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 175, in permission_denied
    raise exceptions.PermissionDenied(detail=message, code=code)
rest_framework.exceptions.PermissionDenied: 此操作未授权。Operation is not granted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 466, in handle_exception
    response = exception_handler(exc, context)
  File "C:\Users\lenovo\Desktop\workspace\django-controller\sse\lib\core\exceptions.py", line 62, in exc_exceptions
    return APIResponse(error=error, result=False, msg=msg, headers=header, status=status)
UnboundLocalError: local variable 'header' referenced before assignment
[2022-06-21 15:00:27,627] [INFO] [Thread-126 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/scenario/9dc6ad3b71fc425f8ff7fd49de20284f/ with method: PUT
[2022-06-21 15:00:30,957] [ERROR] [Thread-127 (process_request_thread)] [django.request] | Internal Server Error: /api/scenario/9dc6ad3b71fc425f8ff7fd49de20284f/
Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\lenovo\Desktop\workspace\django-controller\sse\lib\core\model_view_set.py", line 19, in update
    response = super().update(request, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\mixins.py", line 65, in update
    instance = self.get_object()
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 346, in check_object_permissions
    self.permission_denied(
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 175, in permission_denied
    raise exceptions.PermissionDenied(detail=message, code=code)
rest_framework.exceptions.PermissionDenied: 此操作未授权。Operation is not granted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 466, in handle_exception
    response = exception_handler(exc, context)
  File "C:\Users\lenovo\Desktop\workspace\django-controller\sse\lib\core\exceptions.py", line 62, in exc_exceptions
    return APIResponse(error=error, result=False, msg=msg, headers=header, status=status)
UnboundLocalError: local variable 'header' referenced before assignment
[2022-06-21 15:00:30,963] [INFO] [Thread-127 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/scenario/9dc6ad3b71fc425f8ff7fd49de20284f/ with method: PUT
[2022-06-21 15:00:35,772] [ERROR] [Thread-128 (process_request_thread)] [django.request] | Internal Server Error: /api/scenario/9dc6ad3b71fc425f8ff7fd49de20284f/
Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\lenovo\Desktop\workspace\django-controller\sse\lib\core\model_view_set.py", line 19, in update
    response = super().update(request, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\mixins.py", line 65, in update
    instance = self.get_object()
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 346, in check_object_permissions
    self.permission_denied(
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 175, in permission_denied
    raise exceptions.PermissionDenied(detail=message, code=code)
rest_framework.exceptions.PermissionDenied: 此操作未授权。Operation is not granted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 466, in handle_exception
    response = exception_handler(exc, context)
  File "C:\Users\lenovo\Desktop\workspace\django-controller\sse\lib\core\exceptions.py", line 62, in exc_exceptions
    return APIResponse(error=error, result=False, msg=msg, headers=header, status=status)
UnboundLocalError: local variable 'header' referenced before assignment
[2022-06-21 15:00:35,791] [INFO] [Thread-128 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/scenario/9dc6ad3b71fc425f8ff7fd49de20284f/ with method: PUT
[2022-06-21 15:01:55,546] [INFO] [MainThread] [django.utils.autoreload] | C:\Users\lenovo\Desktop\workspace\django-controller\sse\lib\core\exceptions.py changed, reloading.
[2022-06-21 15:02:03,253] [ERROR] [Thread-1 (process_request_thread)] [sse.lib.utils.logger] | An error occurred:{'msg': '数据校验不通过,Invalid data', 'result': False, 'error': {'code': 'permission_denied', 'message': ErrorDetail(string='此操作未授权。Operation is not granted', code='permission_denied')}}
[2022-06-21 15:02:03,254] [INFO] [Thread-1 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/scenario/9dc6ad3b71fc425f8ff7fd49de20284f/ with method: PUT
[2022-06-21 15:02:03,254] [WARNING] [Thread-1 (process_request_thread)] [django.request] | Bad Request: /api/scenario/9dc6ad3b71fc425f8ff7fd49de20284f/
[2022-06-21 15:02:08,623] [ERROR] [Thread-2 (process_request_thread)] [sse.lib.utils.logger] | An error occurred:{'msg': '数据校验不通过,Invalid data', 'result': False, 'error': {'code': 'permission_denied', 'message': ErrorDetail(string='此操作未授权。Operation is not granted', code='permission_denied')}}
[2022-06-21 15:02:08,624] [INFO] [Thread-2 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/scenario/9dc6ad3b71fc425f8ff7fd49de20284f/ with method: PUT
[2022-06-21 15:02:08,624] [WARNING] [Thread-2 (process_request_thread)] [django.request] | Bad Request: /api/scenario/9dc6ad3b71fc425f8ff7fd49de20284f/
[2022-06-21 15:02:23,671] [ERROR] [Thread-3 (process_request_thread)] [sse.lib.utils.logger] | An error occurred:{'msg': '数据校验不通过,Invalid data', 'result': False, 'error': {'code': 'permission_denied', 'message': ErrorDetail(string='此操作未授权。Operation is not granted', code='permission_denied')}}
[2022-06-21 15:02:23,671] [INFO] [Thread-3 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/scenario/9dc6ad3b71fc425f8ff7fd49de20284f/ with method: PUT
[2022-06-21 15:02:23,672] [WARNING] [Thread-3 (process_request_thread)] [django.request] | Bad Request: /api/scenario/9dc6ad3b71fc425f8ff7fd49de20284f/
[2022-06-21 15:14:21,147] [INFO] [Thread-5 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 15:14:21,150] [INFO] [Thread-4 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 15:14:21,174] [INFO] [Thread-6 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 15:14:25,331] [INFO] [Thread-7 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 15:14:26,231] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_1928D1EBA7A7441086802B675061F707', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_1928D1EBA7A7441086802B675061F707/EXEC_1928D1EBA7A7441086802B675061F707.html', 'duration': '0.15'}.
[2022-06-21 15:14:45,611] [INFO] [Thread-8 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/348e557234fc40369e873de585207bb4/ with method: GET
[2022-06-21 15:14:47,664] [INFO] [Thread-9 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 15:14:47,707] [INFO] [Thread-10 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 15:14:47,746] [INFO] [Thread-11 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 15:14:53,093] [INFO] [Thread-12 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/0c758c426d4d42c8bfe54cf9badff477/ with method: GET
[2022-06-21 15:14:56,532] [INFO] [Thread-13 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 15:16:15,400] [INFO] [Thread-14 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/0c758c426d4d42c8bfe54cf9badff477/ with method: GET
[2022-06-21 15:16:21,436] [INFO] [Thread-15 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 16:12:48,021] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_E00827A402924EBCBF97A7D431555406', 'success': False, 'path': 'Report upload failure', 'duration': 0.0}.
[2022-06-21 16:13:08,861] [INFO] [Thread-16 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 16:13:10,090] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_1B2071C375924293875F5B4CB2A12603', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_1B2071C375924293875F5B4CB2A12603/EXEC_1B2071C375924293875F5B4CB2A12603.html', 'duration': '0.15'}.
[2022-06-21 16:17:12,136] [INFO] [Thread-17 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 16:17:13,306] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_E5743254231E41F9838336496D7559BC', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_E5743254231E41F9838336496D7559BC/EXEC_E5743254231E41F9838336496D7559BC.html', 'duration': '0.15'}.
[2022-06-21 16:17:48,627] [INFO] [Thread-18 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 16:17:49,540] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_70D65CC1E75948F2966E836694999C1E', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_70D65CC1E75948F2966E836694999C1E/EXEC_70D65CC1E75948F2966E836694999C1E.html', 'duration': '0.15'}.
[2022-06-21 16:17:56,435] [INFO] [Thread-19 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 16:17:57,253] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_70AD487DD45F4A978522BE48C2A28257', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_70AD487DD45F4A978522BE48C2A28257/EXEC_70AD487DD45F4A978522BE48C2A28257.html', 'duration': '0.15'}.
[2022-06-21 16:18:02,690] [INFO] [Thread-20 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 16:18:03,649] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_F8B3770E13854B77864DD8440109FDAD', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_F8B3770E13854B77864DD8440109FDAD/EXEC_F8B3770E13854B77864DD8440109FDAD.html', 'duration': '0.15'}.
[2022-06-21 17:01:55,027] [INFO] [Thread-21 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 17:01:56,730] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_16E0B3E707674F1F94B4660F5FA8071E', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_16E0B3E707674F1F94B4660F5FA8071E/EXEC_16E0B3E707674F1F94B4660F5FA8071E.html', 'duration': '0.15'}.
[2022-06-21 17:01:58,433] [INFO] [Thread-22 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 17:01:59,475] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_CE9F08AC9EEA4BA3A133EA608DE42AE1', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_CE9F08AC9EEA4BA3A133EA608DE42AE1/EXEC_CE9F08AC9EEA4BA3A133EA608DE42AE1.html', 'duration': '0.15'}.
[2022-06-21 17:02:01,619] [INFO] [Thread-23 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 17:02:02,638] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_4C61AA76768541809AE5D5B06A172F94', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_4C61AA76768541809AE5D5B06A172F94/EXEC_4C61AA76768541809AE5D5B06A172F94.html', 'duration': '0.15'}.
[2022-06-21 17:02:05,142] [INFO] [Thread-24 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 17:02:06,232] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_D3056D9116CE40D99DFA0498C0D6DA89', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_D3056D9116CE40D99DFA0498C0D6DA89/EXEC_D3056D9116CE40D99DFA0498C0D6DA89.html', 'duration': '0.15'}.
[2022-06-21 17:02:37,859] [INFO] [Thread-25 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 17:02:37,878] [INFO] [Thread-26 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 17:02:38,038] [INFO] [Thread-27 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 17:02:39,350] [INFO] [Thread-28 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/ with method: GET
[2022-06-21 17:02:45,242] [INFO] [Thread-29 (process_request_thread)] [sse.lib.utils.logger] | 220 (vsFTPd 3.0.3)
[2022-06-21 17:02:45,258] [INFO] [Thread-29 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report-details/view/ with method: POST
[2022-06-21 17:02:48,655] [INFO] [Thread-30 (process_request_thread)] [sse.lib.utils.logger] | 220 (vsFTPd 3.0.3)
[2022-06-21 17:02:48,666] [INFO] [Thread-30 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report-details/view/ with method: POST
[2022-06-21 17:02:51,866] [INFO] [Thread-31 (process_request_thread)] [sse.lib.utils.logger] | 220 (vsFTPd 3.0.3)
[2022-06-21 17:02:51,877] [INFO] [Thread-31 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report-details/view/ with method: POST
[2022-06-21 17:20:43,432] [INFO] [Thread-32 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 17:20:46,683] [INFO] [Thread-34 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-21 17:20:46,703] [INFO] [Thread-35 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-21 17:20:46,716] [INFO] [Thread-33 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-21 17:20:53,330] [INFO] [Thread-36 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/batch-execute/ with method: POST
[2022-06-21 17:20:54,457] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_0ED0EB551AD242368F6125275DB8A454', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_0ED0EB551AD242368F6125275DB8A454/EXEC_0ED0EB551AD242368F6125275DB8A454.html', 'duration': '0.15'}.
[2022-06-21 17:21:15,577] [INFO] [Thread-37 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/0c758c426d4d42c8bfe54cf9badff477/ with method: GET
[2022-06-21 17:21:19,212] [INFO] [Thread-38 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 17:34:21,449] [INFO] [Thread-39 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 17:56:50,590] [INFO] [Thread-40 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 17:59:26,386] [INFO] [Thread-41 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 18:01:54,923] [INFO] [Thread-42 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/0c758c426d4d42c8bfe54cf9badff477/ with method: GET
[2022-06-21 18:01:58,916] [INFO] [Thread-43 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/0c758c426d4d42c8bfe54cf9badff477/ with method: GET
[2022-06-21 18:02:04,087] [INFO] [Thread-44 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 18:02:12,044] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_365E73F464794CFDB5528E0A582BA526', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_365E73F464794CFDB5528E0A582BA526/EXEC_365E73F464794CFDB5528E0A582BA526.html', 'duration': '0.15'}.
[2022-06-21 18:04:10,402] [INFO] [Thread-45 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 18:04:12,000] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_DA9B62CD127F4B30B1894925BCDADEB1', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_DA9B62CD127F4B30B1894925BCDADEB1/EXEC_DA9B62CD127F4B30B1894925BCDADEB1.html', 'duration': '0.15'}.
[2022-06-21 18:05:44,827] [INFO] [Thread-46 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-21 18:05:45,976] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_E6C2252248F54CFE861946BC0BDF2F85', 'success': True, 'path': '/home/volume/incoming/20220621/EXEC_E6C2252248F54CFE861946BC0BDF2F85/EXEC_E6C2252248F54CFE861946BC0BDF2F85.html', 'duration': '0.15'}.
[2022-06-21 18:07:20,857] [INFO] [Thread-47 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/0c758c426d4d42c8bfe54cf9badff477/ with method: GET
[2022-06-21 18:07:25,659] [INFO] [Thread-48 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-22 08:52:18,292] [INFO] [Thread-49 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /user/login/ with method: POST
[2022-06-22 08:52:21,173] [INFO] [Thread-50 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/ with method: GET
[2022-06-22 08:52:29,553] [INFO] [Thread-51 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-22 08:52:29,561] [INFO] [Thread-52 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/scenario/ with method: GET
[2022-06-22 08:52:59,305] [INFO] [Thread-53 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-22 08:52:59,342] [INFO] [Thread-54 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-22 08:52:59,364] [INFO] [Thread-55 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-22 08:53:18,077] [INFO] [Thread-56 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/348e557234fc40369e873de585207bb4/ with method: PUT
[2022-06-22 08:53:18,134] [INFO] [Thread-57 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-22 08:53:24,640] [INFO] [Thread-58 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/348e557234fc40369e873de585207bb4/ with method: PUT
[2022-06-22 08:53:24,681] [INFO] [Thread-59 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-22 08:53:26,912] [INFO] [Thread-60 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/348e557234fc40369e873de585207bb4/ with method: PUT
[2022-06-22 08:53:28,645] [INFO] [Thread-61 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/348e557234fc40369e873de585207bb4/ with method: PUT
[2022-06-22 08:54:05,380] [INFO] [Thread-62 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/0c758c426d4d42c8bfe54cf9badff477/ with method: GET
[2022-06-22 08:54:09,339] [INFO] [Thread-63 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-22 09:02:15,799] [INFO] [Thread-64 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-22 09:02:16,635] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_5C99BC68DEDE45E0A7BF7D80FE5E69BF', 'success': True, 'path': '/home/volume/incoming/20220622/EXEC_5C99BC68DEDE45E0A7BF7D80FE5E69BF/EXEC_5C99BC68DEDE45E0A7BF7D80FE5E69BF.html', 'duration': '0.15'}.
[2022-06-22 09:07:32,300] [INFO] [Thread-65 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-22 09:15:38,813] [INFO] [Thread-66 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-22 09:15:40,110] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_162B81B917C04F02B9850F59269F7F25', 'success': True, 'path': '/home/volume/incoming/20220622/EXEC_162B81B917C04F02B9850F59269F7F25/EXEC_162B81B917C04F02B9850F59269F7F25.html', 'duration': '0.15'}.
[2022-06-22 09:28:33,197] [INFO] [Thread-67 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-22 09:31:32,942] [INFO] [Thread-68 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-22 09:35:24,617] [INFO] [Thread-69 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-22 09:37:39,433] [INFO] [Thread-70 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-22 09:42:56,832] [INFO] [Thread-71 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-22 09:42:57,641] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_737362CF58294708A75A34E15ABDA03D', 'success': True, 'path': '/home/volume/incoming/20220622/EXEC_737362CF58294708A75A34E15ABDA03D/EXEC_737362CF58294708A75A34E15ABDA03D.html', 'duration': '0.15'}.
[2022-06-22 09:48:10,518] [INFO] [Thread-72 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-22 09:51:24,307] [INFO] [Thread-73 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-22 09:54:46,303] [INFO] [Thread-74 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-22 09:58:21,402] [INFO] [Thread-75 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-22 09:59:53,078] [INFO] [Thread-76 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/0c758c426d4d42c8bfe54cf9badff477/ with method: GET
[2022-06-22 10:00:24,568] [INFO] [Thread-77 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-22 10:34:48,407] [INFO] [Thread-78 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-22 10:34:49,156] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_1500E08529BA49D4A97604EA8F2262A6', 'success': True, 'path': '/home/volume/incoming/20220622/EXEC_1500E08529BA49D4A97604EA8F2262A6/EXEC_1500E08529BA49D4A97604EA8F2262A6.html', 'duration': '0.15'}.
[2022-06-22 10:39:26,854] [INFO] [Thread-79 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-22 10:39:27,094] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_0099C2C327394EF692CC487221DB0066', 'success': False, 'path': 'Report upload failure', 'duration': 0.0}.
[2022-06-22 10:43:58,195] [INFO] [Thread-80 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/0c758c426d4d42c8bfe54cf9badff477/ with method: GET
[2022-06-22 10:44:08,558] [INFO] [Thread-81 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/execute/ with method: POST
[2022-06-22 10:44:08,669] [INFO] [MainThread] [sse.lib.utils.logger] | The received response from execution engine is:{'exec_id': 'EXEC_3EDF16DF4F644B1EB92C6BA93FE1FE4C', 'success': False, 'path': 'Execution error', 'duration': 0.0}.
[2022-06-22 10:45:22,834] [INFO] [Thread-82 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/suit/ with method: GET
[2022-06-22 10:45:22,873] [INFO] [Thread-83 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/template/ with method: GET
[2022-06-22 10:45:22,900] [INFO] [Thread-84 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-22 10:45:24,328] [INFO] [Thread-85 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/case/ with method: GET
[2022-06-22 10:45:24,337] [INFO] [Thread-86 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/scenario/ with method: GET
[2022-06-22 10:45:24,966] [INFO] [Thread-87 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report/ with method: GET
[2022-06-22 10:45:28,184] [INFO] [Thread-88 (process_request_thread)] [sse.lib.utils.logger] | 220 (vsFTPd 3.0.3)
[2022-06-22 10:45:28,261] [ERROR] [Thread-88 (process_request_thread)] [django.request] | Internal Server Error: /api/report-details/view/
Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\lenovo\Desktop\workspace\django-controller\sse\applications\api\views.py", line 214, in report_view
    ftp.download_file(ant_report_dir, remote_path)
  File "C:\Users\lenovo\Desktop\workspace\django-controller\sse\lib\utils\FtpUtils.py", line 123, in download_file
    self.obj.retrbinary('RETR %s' % remote_file_path, file_handle.write)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\ftplib.py", line 436, in retrbinary
    with self.transfercmd(cmd, rest) as conn:
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\ftplib.py", line 393, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\ftplib.py", line 359, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\ftplib.py", line 281, in sendcmd
    return self.getresp()
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\ftplib.py", line 254, in getresp
    raise error_perm(resp)
ftplib.error_perm: 550 Failed to open file.
[2022-06-22 10:45:28,265] [INFO] [Thread-88 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report-details/view/ with method: POST
[2022-06-22 10:45:31,372] [INFO] [Thread-89 (process_request_thread)] [sse.lib.utils.logger] | 220 (vsFTPd 3.0.3)
[2022-06-22 10:45:31,399] [ERROR] [Thread-89 (process_request_thread)] [django.request] | Internal Server Error: /api/report-details/view/
Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\lenovo\Desktop\workspace\django-controller\sse\applications\api\views.py", line 214, in report_view
    ftp.download_file(ant_report_dir, remote_path)
  File "C:\Users\lenovo\Desktop\workspace\django-controller\sse\lib\utils\FtpUtils.py", line 123, in download_file
    self.obj.retrbinary('RETR %s' % remote_file_path, file_handle.write)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\ftplib.py", line 436, in retrbinary
    with self.transfercmd(cmd, rest) as conn:
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\ftplib.py", line 393, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\ftplib.py", line 359, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\ftplib.py", line 281, in sendcmd
    return self.getresp()
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python310\lib\ftplib.py", line 254, in getresp
    raise error_perm(resp)
ftplib.error_perm: 550 Failed to open file.
[2022-06-22 10:45:31,402] [INFO] [Thread-89 (process_request_thread)] [sse.lib.utils.logger] | Receive request from IP: 127.0.0.1 by url: /api/report-details/view/ with method: POST
[2022-06-22 10:47:46,575] [INFO] [MainThread] [django.utils.autoreload] | C:\Users\lenovo\Desktop\workspace\django-controller\sse\celery_job\tasks.py changed, reloading.
